(deftheme darktooth
  "Created 2016-03-29.")

(custom-theme-set-variables
 'darktooth
 '(ansi-color-names-vector ["#3C3836" "#FB4934" "#B8BB26" "#FABD2F" "#83A598" "#D3869B" "#8EC07C" "#EBDBB2"]))

(custom-theme-set-faces
 'darktooth
 '(cursor ((t (:background "#FDF4C1"))))
 '(link ((t (:foreground "#83A598" :underline t))))
 '(link-visited ((t (:foreground "#83A598" :underline nil))))
 '(mode-line ((t (:foreground "#EBDBB2" :background "#1D2021" :box nil))))
 '(mode-line-inactive ((t (:foreground "#A89984" :background "#504945" :box nil))))
 '(fringe ((t (:background "#282828"))))
 '(hl-line ((t (:background "#2B3C44"))))
 '(region ((t (:background "#30434C" :distant-foreground "#FDF4C1"))))
 '(secondary-selection ((t (:background "#2B3C44"))))
 '(header-line ((t (:foreground "#61ACBB" :background "#282828" :bold nil))))
 '(minibuffer-prompt ((t (:foreground "#61ACBB" :background "#282828" :bold nil))))
 '(font-lock-builtin-face ((t (:foreground "#FE8019"))))
 '(font-lock-constant-face ((t (:foreground "#BBAA97"))))
 '(font-lock-comment-face ((t (:foreground "#7C6F64"))))
 '(font-lock-function-name-face ((t (:foreground "#A89984"))))
 '(font-lock-keyword-face ((t (:foreground "#DD6F48"))))
 '(font-lock-string-face ((t (:foreground "#528B8B"))))
 '(font-lock-variable-name-face ((t (:foreground "#83A598"))))
 '(font-lock-type-face ((t (:foreground "#66999D"))))
 '(font-lock-warning-face ((t (:foreground "#FB4934" :bold t))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#5C7E81"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#837486"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#9C6F68"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#7B665C"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#5C7E81"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#837486"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#9C6F68"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#7B665C"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#5C7E81"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#FDF4C1" :background nil))))
 '(ido-first-match ((t (:foreground "#61ACBB" :background "#1D2021"))))
 '(ido-only-match ((t (:foreground "#528B8B"))))
 '(sp-pair-overlay-face ((t (:background "#504945"))))
 '(sp-show-pair-match-face ((t (:background "#504945"))))
 '(sp-show-pair-mismatch-face ((t (:background "#FB4934"))))
 '(js2-warning ((t (:underline (:color "#FABD2F" :style wave)))))
 '(js2-error ((t (:underline (:color "#FB4933" :style wave)))))
 '(js2-external-variable ((t (:underline (:color "#8EC07C" :style wave)))))
 '(js2-jsdoc-tag ((t (:foreground "#928374" :background nil))))
 '(js2-jsdoc-type ((t (:foreground "#A89984" :background nil))))
 '(js2-jsdoc-value ((t (:foreground "#BDAE93" :background nil))))
 '(js2-function-param ((t (:foreground "#8EC07C" :background nil))))
 '(js2-function-call ((t (:foreground "#83A598" :background nil))))
 '(js2-instance-member ((t (:foreground "#FE8019" :background nil))))
 '(js2-private-member ((t (:foreground "#B57614" :background nil))))
 '(js2-private-function-call ((t (:foreground "#427B58" :background nil))))
 '(js2-jsdoc-html-tag-name ((t (:foreground "#A89984" :background nil))))
 '(js2-jsdoc-html-tag-delimiter ((t (:foreground "#BDAE93" :background nil))))
 '(org-agenda-date-today ((t (:foreground "#D5C4A1" :slant italic :weight bold))))
 '(org-agenda-structure ((t (:inherit font-lock-comment-face))))
 '(org-archived ((t (:foreground "#FDF4C1" :weight bold))))
 '(org-checkbox ((t (:foreground "#D5C4A1" :background "#282828" :box (:line-width 1 :style released-button)))))
 '(org-date ((t (:foreground "#076678" :underline t))))
 '(org-done ((t (:foreground "#B8BB26" :bold t :weight bold))))
 '(org-formula ((t (:foreground "#FABD2F"))))
 '(org-headline-done ((t (:foreground "#B8BB26"))))
 '(org-hide ((t (:foreground "#282828"))))
 '(org-level-1 ((t (:foreground "#FE8019"))))
 '(org-level-2 ((t (:foreground "#B8BB26"))))
 '(org-level-3 ((t (:foreground "#83A598"))))
 '(org-level-4 ((t (:foreground "#FABD2F"))))
 '(org-level-5 ((t (:foreground "#427B58"))))
 '(org-level-6 ((t (:foreground "#B8BB26"))))
 '(org-level-7 ((t (:foreground "#FB4933"))))
 '(org-level-8 ((t (:foreground "#83A598"))))
 '(org-link ((t (:foreground "#FABD2F" :underline t))))
 '(org-scheduled ((t (:foreground "#B8BB26"))))
 '(org-scheduled-previously ((t (:foreground "#FB4933"))))
 '(org-scheduled-today ((t (:foreground "#83A598"))))
 '(org-sexp-date ((t (:foreground "#83A598" :underline t))))
 '(org-special-keyword ((t (:inherit font-lock-comment-face))))
 '(org-table ((t (:foreground "#B8BB26"))))
 '(org-tag ((t (:bold t :weight bold))))
 '(org-time-grid ((t (:foreground "#FE8019"))))
 '(org-todo ((t (:foreground "#FB4933" :weight bold :bold t))))
 '(org-upcoming-deadline ((t (:inherit font-lock-keyword-face))))
 '(org-warning ((t (:foreground "#FB4933" :weight bold :underline nil :bold t))))
 '(org-column ((t (:background "#282828"))))
 '(org-column-title ((t (:background "#1D2021" :underline t :weight bold))))
 '(org-mode-line-clock ((t (:foreground "#D5C4A1" :background "#282828"))))
 '(org-mode-line-clock-overrun ((t (:foreground "#000000" :background "#FB4933"))))
 '(org-ellipsis ((t (:foreground "#FABD2F" :underline t))))
 '(org-footnote ((t (:foreground "#427B58" :underline t))))
 '(lazy-highlight ((t (:foreground "#FDF4C1" :background "#504945"))))
 '(highlight ((t (:foreground "#FFFFC8" :background "#076678"))))
 '(match ((t (:foreground "#FDF4C1" :background "#504945"))))
 '(isearch ((t (:foreground "#FDF4C1" :background "#427B58"))))
 '(isearch-fail ((t (:foreground "#FFFFC8" :background "#9D0006"))))
 '(show-paren-match ((t (:foreground "#FDF4C1" :background "#076678"))))
 '(show-paren-mismatch ((t (:foreground "#FFFFC8" :background "#9D0006"))))
 '(anzu-mode-line ((t (:foreground "#FDF4C1" :height 100 :background "#076678"))))
 '(popup-face ((t (:foreground "#FDF4C1" :background "#3C3836"))))
 '(popup-menu-mouse-face ((t (:foreground "#FDF4C1" :background "#076678"))))
 '(popup-menu-selection-face ((t (:foreground "#FDF4C1" :background "#076678"))))
 '(popup-tip-face ((t (:foreground "#FFFFC8" :background "#36473A"))))
 '(company-echo ((t (:inherit company-echo-common))))
 '(company-echo-common ((t (:foreground "#83A598" :background nil))))
 '(company-preview ((t (:inherit company-preview-common))))
 '(company-preview-search ((t (:inherit company-preview-common))))
 '(company-scrollbar-fg ((t (:foreground nil :background "#504945"))))
 '(company-scrollbar-bg ((t (:foreground nil :background "#665C54"))))
 '(company-tooltip ((t (:foreground "#FFFFC8" :background "#3C3836"))))
 '(company-preview-common ((t (:inherit font-lock-comment-face))))
 '(company-tooltip-common ((t (:foreground "#FDF4C1" :background "#3C3836"))))
 '(company-tooltip-annotation ((t (:foreground "#83A598" :background "#3C3836"))))
 '(company-tooltip-common-selection ((t (:foreground "#FDF4C1" :background "#076678"))))
 '(company-tooltip-mouse ((t (:foreground "#282828" :background "#83A598"))))
 '(company-tooltip-selection ((t (:foreground "#FDF4C1" :background "#076678"))))
 '(helm-action ((t (:foreground "#FFFFFF" :underline t))))
 '(helm-candidate-number ((t (:foreground "#B8BB26"))))
 '(helm-grep-cmd-line ((t (:foreground "#B8BB26"))))
 '(helm-grep-file ((t (:foreground "#8F3F71"))))
 '(helm-grep-finish ((t (:foreground "#61ACBB"))))
 '(helm-grep-lineno ((t (:foreground "#FE8019"))))
 '(helm-grep-match ((t (:foreground "#FABD2F"))))
 '(helm-header ((t (:foreground "#83A598"))))
 '(helm-helper ((t (:foreground "#83A598"))))
 '(helm-match ((t (:foreground "#FE8019"))))
 '(helm-moccur-buffer ((t (:foreground "#8EC07C" :underline t))))
 '(helm-prefarg ((t (:foreground "#61ACBB"))))
 '(helm-selection ((t (:foreground "#FFFFFF" :background "#504945"))))
 '(helm-selection-line ((t (:foreground "#FFFFFF" :background "#504945"))))
 '(helm-separator ((t (:foreground "#9D0006"))))
 '(helm-source-header ((t (:foreground "#D5C4A1" :background "#3C3836"))))
 '(helm-visible-mark ((t (:foreground "#000000" :background "#BDAE93"))))
 '(default ((t (:foreground "#FDF4C1" :background "#282828")))))

(provide-theme 'darktooth)
